# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 我是美宝宝
name: 美宝宝 
email: 1347467979@qq.com
location: hangzhou,china # ex. Nice, France
github_url: https://github.com/huxiamei # ex. https://github.com/DONGChuan
cnblog_url: https://home.cnblogs.com/u/huxiamei/
description: It's a colorful world
